task:
  name: FreeBSD
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  test_script:
    - pkg install -y perl5
    - pkg install -y bash
    - pkg install -y git
    - echo|cpan App::cpanminus
    - cpanm --quiet --notest File::ShareDir::Install
    - cpanm --quiet --notest XML::XPath
    - cpanm --quiet --notest DBM::Deep
    - cpanm --quiet --notest Digest::MD5
    - cpanm --quiet --notest File::Find::Rule
    - cpanm --quiet --notest Spreadsheet::ParseExcel
    - cpanm --quiet --notest Text::CSV_XS
    - cpanm --quiet --notest LWP::Protocol::https
    - cpanm --installdeps .
    - ./build-data.sh
    - perl Makefile.PL
    - make
    - make test

task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-11.3.1
  test_script:
    - echo|cpan App::cpanminus
    - export PERL5LIB=/Users/anka/perl5/lib/perl5
    - /Users/anka/perl5/bin/cpanm --quiet --notest File::ShareDir::Install
    - /Users/anka/perl5/bin/cpanm --quiet --notest XML::XPath
    - /Users/anka/perl5/bin/cpanm --quiet --notest DBM::Deep
    - /Users/anka/perl5/bin/cpanm --quiet --notest Digest::MD5
    - /Users/anka/perl5/bin/cpanm --quiet --notest File::Find::Rule
    - /Users/anka/perl5/bin/cpanm --quiet --notest Spreadsheet::ParseExcel
    - /Users/anka/perl5/bin/cpanm --quiet --notest Text::CSV_XS
    - /Users/anka/perl5/bin/cpanm --quiet --notest LWP::Protocol::https
    - /Users/anka/perl5/bin/cpanm --installdeps .
    - ./build-data.sh
    - perl Makefile.PL
    - make
    - make test
