task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  test_script:
    - echo|cpan App::cpanminus
    - export PERL5LIB=/Users/admin/perl5/lib/perl5
    - /Users/admin/perl5/bin/cpanm --quiet --notest File::ShareDir::Install
    - /Users/admin/perl5/bin/cpanm --quiet --notest XML::XPath
    - /Users/admin/perl5/bin/cpanm --quiet --notest DBM::Deep
    - /Users/admin/perl5/bin/cpanm --quiet --notest Digest::MD5
    - /Users/admin/perl5/bin/cpanm --quiet --notest File::Find::Rule
    - /Users/admin/perl5/bin/cpanm --quiet --notest Spreadsheet::XLSX
    - /Users/admin/perl5/bin/cpanm --quiet --notest Text::CSV_XS
    - /Users/admin/perl5/bin/cpanm --quiet --notest LWP::Protocol::https
    - /Users/admin/perl5/bin/cpanm --quiet --notest Test2
    - rm /Users/admin/.cpanm/work/*/build.log
    - /Users/admin/perl5/bin/cpanm --installdeps . || cat /Users/admin/.cpanm/work/*/build.log
    - ./build-data.sh
    - perl Makefile.PL
    - make
    - make test
