language: perl
env:
  global:
    - PERL_USE_UNSAFE_INC=0
    - AUTOMATED_TESTING=1
perl:
  - "5.8"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
matrix:
  include:
    - perl: "5.20"
      before_install:
        - cpanm --quiet --notest Devel::Cover::Report::Coveralls
        # eeuuww, repetition from the global 'before_install'
        - cpanm --quiet --notest File::ShareDir::Install
        - cpanm --quiet --notest XML::XPath
        - cpanm --quiet --notest DBM::Deep
        - cpanm --quiet --notest Digest::MD5
        - cpanm --quiet --notest File::Find::Rule
        - cpanm --quiet --notest Spreadsheet::ParseExcel
        - cpanm --quiet --notest Text::CSV_XS
        - cpanm --quiet --notest LWP::Protocol::https
        - ./build-data.sh
        # repetition ends here
      script: "perl Makefile.PL && make && cover -ignore blib/lib/Number/Phone/UK/Data.pm -test -report coveralls"
        # -ignore blib/lib/Number/Phone/StubCountry/??.pm -ignore blib/lib/Number/Phone/NANP/??.pm
before_install:
  - cpanm --quiet --notest File::ShareDir::Install
  - cpanm --quiet --notest XML::XPath
  - cpanm --quiet --notest DBM::Deep
  - cpanm --quiet --notest Digest::MD5
  - cpanm --quiet --notest File::Find::Rule
  - cpanm --quiet --notest Spreadsheet::ParseExcel
  - cpanm --quiet --notest Text::CSV_XS
  - cpanm --quiet --notest LWP::Protocol::https
  - ./build-data.sh
sudo: false
