language: perl
matrix:
  include:
    - perl: "5.20"
      env: AUTOMATED_TESTING=1
      dist: trusty
      before_install:
        - cpanm --quiet --notest Devel::Cover::Report::Coveralls
        - cpanm --quiet --notest File::ShareDir::Install XML::XPath DBM::Deep Digest::MD5 File::Find::Rule Spreadsheet::XLSX Text::CSV_XS LWP::Protocol::https
        - ./build-data.sh
      script: "perl Makefile.PL && make && cover -ignore blib/lib/Number/Phone/UK/Data.pm -test -report coveralls"
sudo: false
