on: [push, pull_request]
name: FreeBSD

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage parent
          cpanm File::ShareDir::Install XML::XPath
          cpanm File::Find::Rule Text::CSV_XS LWP::Protocol::https
          cpanm --installdeps .
          perl Makefile.PL
          ./build-data.sh
          make test
          make dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-for-freebsd-install
          path: '*.tar.gz'
          retention-days: 1
  install-freebsd:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: dist-for-freebsd-install
      - name: Install on FreeBSD
        uses: cross-platform-actions/action@v0.26.0
        with:
          operating_system: freebsd
          version: 13.1
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            sudo pkg install -y perl5 &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .
