on: [push, pull_request]
name: Linux

jobs:

  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        arch: [ 'ia32', 'arm6' ]
    name: Linux on ${{ matrix.arch }}
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: build perl
        run: |
            curl -L https://install.perlbrew.pl | bash
            source ~/perl5/perlbrew/etc/bashrc
            perlbrew init
            perlbrew install -v perl-5.30.3
            perlbrew switch perl-5.30.3
            perlbrew install-cpanm -f
            perl -V
            cpanm TAP::Harness::Env

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm --quiet --notest ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage parent
            cpanm --quiet --notest File::ShareDir::Install XML::XPath DBM::Deep Digest::MD5 File::Find::Rule Spreadsheet::XLSX Text::CSV_XS LWP::Protocol::https
            cpanm --quiet --notest --installdeps .
            ./build-data.sh
            perl Makefile.PL
            make test
