on: [push, pull_request]
name: Linux

jobs:

  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5.38', '5.36', '5.30', '5.26', '5.22', '5.16' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - name: check out code
        uses: actions/checkout@v5

      - name: switch to perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm --quiet --notest ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage parent
            cpanm --quiet --notest File::ShareDir::Install XML::XPath Data::CompactReadonly File::Find::Rule Text::CSV_XS LWP::Protocol::https
            cpanm --quiet --notest --installdeps .
            ./build-data.sh
            perl Makefile.PL
            make test TEST_VERBOSE=1
