on: [push, pull_request]
name: OpenBSD

jobs:
  build:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --quiet --notest ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage parent
          cpanm --quiet --notest File::ShareDir::Install XML::XPath
          cpanm --quiet --notest File::Find::Rule Spreadsheet::XLSX Text::CSV_XS LWP::Protocol::https
          cpanm --quiet --notest --installdeps .
          perl Makefile.PL
          ./build-data.sh
          make test
          make dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist-for-openbsd-install
          path: '*.tar.gz'
          retention-days: 1
  install-openbsd:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-for-openbsd-install
      - name: Install on OpenBSD
        uses: cross-platform-actions/action@v0.17.0
        with:
          operating_system: openbsd
          version: 6.9
          shell: bash
          run: |
            mkdir dist-for-test &&
            tar -C dist-for-test -xzf *.tar.gz &&
            cd dist-for-test/* &&
            cpan App::cpanminus &&
            /home/runner/perl5/bin/cpanm --quiet --notest --installdeps . &&
            /home/runner/perl5/bin/cpanm -v .
